from snakemake.utils import validate
import pandas as pd
import os


# ----- load config file ----- #

configfile: "config/config.yml"

# ----- define functions ----- #

def _read_samples(infile):
  m = pd.read_csv(infile, sep='\t', index_col=0, header=None)
  return set(m.index)

samples = _read_samples(config["samples"])

# ----- start execution of the rules ----- #

rule run_blastn:
  input:
    expand("out/blast/{sample}.txt", sample=samples)

rule blastn:
  input:
    query="db/virulence.fasta",
    nucl=lambda wildcards: config["fastas"] + wildcards.sample + ".fna"
  output:
    blast="out/blast/{sample}.txt"
  threads: 4
  log: "out/logs/blast_{sample}.log"
  conda: "envs/blast.yml"
  shell:
    """
    blastn -query {input.query} -subject {input.nucl} -out {output.blast} -outfmt "6 qseqid sseqid pident qlen slen length nident"
    """

rule summary:
  input:
      blastdir=config["blastdir"],
      vir=config["virlist"]
  log: "out/logs/summary.log"
  shell:
    """
    python workflow/scripts/blast_output.py {input.blastdir} {input.vir}
    """
