
# ----- params ----- #
virlist: "virulence.csv"

# ----- inputs ----- #
# list of sample names without extension or path
samples: "samples_test.txt"
# path to fastas
fastas: "test/"

# ----- outputs ----- #
blastdir: "out/blast/"
